name: ci

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: virtool/create-sample:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
  release:
    needs: [build]
    name: release
    outputs:
      git-tag: ${{ steps.semantic.outputs.git-tag }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install semantic-release
        run: npm i semantic-release@v24.2.5 @semantic-release/exec@v7.1.0 conventional-changelog-conventionalcommits@9.0.0
      - name: Run semantic-release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
  ghcr:
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'Virtool' && github.event_name == 'push' && needs.release.outputs.git-tag != ''
    needs: [release]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ needs.release.outputs.git-tag }}
    - uses: snok/install-poetry@v1
    - name: Write VERSION file
      run: echo ${{ needs.release.outputs.git-tag }} > VERSION
    - name: Update Version
      run: poetry version ${{ needs.release.outputs.git-tag }}
    - uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        context: git
        images: ${{ env.REGISTRY }}/virtool/create-sample
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
