name: ci

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install semantic-release
        run: npm i semantic-release@v24.2.5 conventional-changelog-conventionalcommits@9.0.0
      - name: Release
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release