name: release

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  ghcr:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    if: github.repository_owner == 'Virtool'
    steps:
    - uses: actions/checkout@v2
    - uses: snok/install-poetry@v1
    - name: Write VERSION file
      run: echo ${{ github.event.release.tag_name }} > VERSION
    - name: Update Version
      run: poetry version ${{github.event.release.tag_name}}
    - uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/virtool/create-sample
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
